language: node_js
env:
  global:
    - secure: "JonR5GJedv/SbYQrYAhjFBUsF02GSUq8Fuk0wQRaOY1E/aBxfqLLVp6efaYYG9YMPkklHOu+HWSwVO0X6AeKblEb+4/h8oCUC4Q4KwXTF5xznVp/Bs98hPtqMmYT3XAIe13HeV5hbV4tKMtVYpwm8h4ZVhs1eUpnNpiVgUyWRqE="
    - secure: "nbOagqTMyLRwN5E3zNuqkuq6IMmHRFKqcWNQauSICzZ629woRhLkofqPeLI9sJNvF13GT6BWJfroE45+juKSgbs27rtRp6/cN90/r+Jv1+STInobowcqJM2HoG2bGQ08Vx/P1PYJQF8X6ai6xFmTEuOhrew95S97ZUmu1adNsq4="
    - secure: "Tye6/rssYfBQp+euo7fnSs7S+/hmCkBT1u0CWzW5R0mHRRpZf5MQRonqHwXrypFtHoZuLlqmJC7woy5T+yuyNZoGNL5r19kSlOWCcFDvDCZD/qghq9DoKN+u9AAoIu7phSNa0ve86NZM91hvad8evkRoIaHM2umjkx8fSmMRjkY="
    - DEPLOY_BETA_PATH=/var/www/betahelp/
    - DEPLOY_PROD_PATH=/var/www/help/
node_js:
  - 8
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn run build
after_success:
  - echo "App install Success"
  - openssl aes-256-cbc -K $encrypted_17bd2ea19db8_key -iv $encrypted_17bd2ea19db8_iv -in .travis.deploy.enc -out .travis.deploy -d
  - chmod 600 .travis.deploy
  - 'test $TRAVIS_BRANCH == "develop" && rsync -avz -e "ssh -i .travis.deploy -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete -P ./dist/ "$DEPLOY_USER"@"$DEPLOY_IP":"$DEPLOY_BETA_PATH"'
  - 'test $TRAVIS_BRANCH == "master" && rsync -avz -e "ssh -i .travis.deploy -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete -P ./dist/ "$DEPLOY_USER"@"$DEPLOY_IP":"$DEPLOY_PROD_PATH"'
# notifications:
#   slack:
#     secure: t9rCkpP1s3kCdoM3DhcBSOjYK7iQgWzhAO2Dq44Tns3Lf1T+P0EAKuAI1ARjhdiskhkKxzIzsOrEJOVy/DIvnWfh1Q0ZrRAkx4aGbgJpIaJEULcFf5/cAlpR01fLf1wjqTb8JQOpIr01c7fpYjVu6OFEujpAxzAH2Y/nHorOYWM7itISnEhay41M8XBpQmsGMZF3GWn8KMGZSI7W+kl71FwW3/LWxDLY4NO1vPXttJAKqGtnGEJsDKzhD03nw8oGfBPK8HhCUKikzWr76BndEPmeh5k0+LGIpRn4gKb5Y9eglvtSAt6jdj4ljaW4NcRkBzNxFGgxCdU4FbMH7h778j67LgoQ8xVSkZoqBhup1tIOmScayiptCKgO1d1a1CEaxFFqvvLFFJ60IS5AOjMApmupwNaJZxrySJvJPUZsf0EbemRdqynGST1zcZkTCOPjjuFjqrTEY9umklQG1qSQ0RgfjKg8cDdFLTzHvC8Vki9rYqhGjdFW/sTwcHX9FZxy6goSQJQQaJtcMOelQJQOrLvZYzL4SDOGFLmMyMFmdtJjHnqDQgLjbseU7GRztW2IW4wZcE9vi9oBo5fiCaGe8PWsV020P26AiRsZ0n9LNCVRQLjL+/fX3ckj81iE7FEEUdWI4n4BTNcu5+Uc93h0RgnTj99iVMwBv/3AkToCsEQ=
